name: Error numbers
on:
  pull_request:
    paths:
      - '.github/workflows/errno.yml'
      - 'lib/libc/minimal/include/errno.h'
      - 'scripts/ci/errno.py'

permissions:
  contents: read

jobs:
  check-errno:
    runs-on: [self-hosted, Linux, zephyr-ci]
    env:
      BASE_REF: ${{ github.event.pull_request.base.ref }}
    steps:
      - name: Checkout
        if: github.event_name == 'pull_request'
        run: |
          sudo rm -rf "$GITHUB_WORKSPACE"/.??* "$GITHUB_WORKSPACE"/*
          GIT_REF="${{ github.event.pull_request.head.sha }}"
          CACHE_DIR="/data/ambiqzephyrcache/zephyrproject/zephyr"
          if [ -d "${CACHE_DIR}" ]; then
            echo "Cloning from local cache (${CACHE_DIR}) at ${GIT_REF}…"
            git clone --reference "${CACHE_DIR}" \
                      --depth 1 \
                      https://github.com/${{ github.repository }}.git "zephyr"
          else
            echo "Cache not found; doing fresh shallow clone at ${GIT_REF}…"
            git clone --depth 1 \
                      https://github.com/${{ github.repository }}.git "zephyr"
          fi
          cd "zephyr"
          git fetch origin "${BASE_REF}"
          git fetch origin "${GIT_REF}"
          git reset --hard "${GIT_REF}"
          git clean -fdx

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.12
          cache: pip
          cache-dependency-path: scripts/requirements-actions.txt

      - name: Install Python packages
        working-directory: zephyr
        run: |
          pip install -r scripts/requirements-actions.txt --require-hashes

      - name: Environment Setup
        run: |
          echo "ZEPHYR_SDK_INSTALL_DIR=/opt/zephyr-sdk-0.17.2" >> $GITHUB_ENV

      - name: Run errno.py
        working-directory: zephyr
        run: |
          export ZEPHYR_BASE=${PWD}
          ./scripts/ci/errno.py
